# documentation for mkdocs.yaml: https://www.mkdocs.org/user-guide/configuration
#####  NOTES 🦆🦆
#   🦆  TABS ( \t ) are not allowed; spaces only 
#       see: https://yaml.org/spec/1.2/spec.html#id2777534
#   🦆   

## Local dev options #####################################

dev_addr: 192.168.8.200:5075
# where to serve local from

## Basic Site Info #####################################

site_name: 🦆🦆🏴 DuckDuckLib

site_description: Firefox search extension that turns "safe search" and regional filtering OFF by default so you can decide what you want to see. 

site_url: https://DuckDuckLib.github.io
# required by the theme Cinder
# see: https://sourcefoundry.org/cinder/#1-set-the-site_url-configuration-field

site_author: CouldBeThis

copyright: GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007  (AGPLv3)

## git & GitHub #####################################

remote_branch: main
# when site uilding by gh-deloy, this sends it to the correct branch
repo_url: https://github.com/DuckDuckLib/DuckDuckLib
repo_name: DuckDuckLib/DuckDuckLib
edit_uri: ""
# edit_url set to empty string as instructed here 
# https://www.mkdocs.org/user-guide/configuration/#edit_uri to prevent adding "edit on github" links. these are contraindicated 
# by use of gh-deploy (see: 
# https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages )

## Theming & Layout #####################################

#theme:
# name: readthedocs
##   hljs_languages:
##       - yaml
##       - rust
# sticky_navigation: true

# Theme: Cider
# docs:   https://sourcefoundry.org/cinder/
# github: https://github.com/chrissimpkins/cinder
#theme:
# name: null
# custom_dir: 'cinder'
# colorscheme: dracula
  # just for code highlighting, I think
  # REMOVED
  # this theme has a bug that I can't resolve without removing 
  # a bunch of stuff from the site
  # see: https://github.com/chrissimpkins/cinder/issues/102

# Theme:  Material for MkDocs
# docs:   https://squidfunk.github.io/mkdocs-material/customization/
# github: https://github.com/squidfunk/mkdocs-material

theme:
  name: material
  font: false
  # disables Google font loading via CDN (if changed, must update Privacy Policy)
  palette:
    scheme: preference
    primary: red
    accent: amber
    # docs: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  logo: images/logos/ddl-icon-128.png
  favicon: images/logos/favicon.ico
  features:
     # docs for all below til otherwise noted:
     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    # "clicks on all internal links will be intercepted and 
    # dispatched via XHR without fully reloading the page"
   
    - navigation.tracking
    # "URL in the address bar is automatically updated with 
    # the active anchor as highlighted in the table of contents."

    - navigation.tabs
    # "top-level sections are rendered in a menu layer below the
    # header for viewports above 1220px, but remain as-is on mobile

    - navigation.expand
    # "left sidebar will expand all collapsible subsections by default"

    - toc.integrate
    # Instead of the page's TOC on the right, it's on the left,
    # integrated with whole site nav, unless tabs is enabled above
    

    - header.autohide
    # "header is automatically hidden when the user scrolls past 
    # a certain threshold"
    # docs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/

## Footer #####################################

extra:
  social:
    - icon: fontawesome/solid/code-branch
      link: https://github.com/DuckDuckLib/DuckDuckLib.github.io
      name: website github repo
    - icon: fontawesome/brands/firefox-browser
      link: https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-safe/
      name: Get it for Firefox
    - icon: fontawesome/solid/envelope
      link: mailto:test@test.com
      name: Send an email top developer
      # docs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#configuration
      # (but I don't think it is theme-specific)

## Navigation (Manual) #####################################    

#nav: 
#disabled because auto-generated is doing fine
#documention if ever required: https://www.mkdocs.org/user-guide/configuration/#nav

## Markdown Extensions #####################################

markdown_extensions:
# docs: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions 
# python-markdown supported by default: https://python-markdown.github.io/extensions/
# 3rd party extension docs: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
#     🦆 when adding 3rd party extensions, update:
#           - docs/development/contributing.md
#           - about/privacy.md
 
  - admonition
  # Admonition | "rST-style admonitions"
  # docs: https://python-markdown.github.io/extensions/admonition/
  # better docs: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  # 
  
  - attr_list
  # Attribute Lists | "syntax to define attributes on the various HTML elements in markdown’s output."
  # docs: https://python-markdown.github.io/extensions/attr_list/

  - codehilite
  # CodeHilite | "code/syntax highlighting to standard Python-Markdown code blocks using Pygments"
  # docs: https://python-markdown.github.io/extensions/code_hilite/

  - fenced_code
  # Fenced Code Blocks | "alternate method of defining code blocks without indentation"
  # docs: https://python-markdown.github.io/extensions/fenced_code_blocks/
  #   and: https://www.mkdocs.org/user-guide/writing-your-docs/#fenced-code-blocks
 
  - meta
  # Meta-Data | "for defining meta-data about a document" | Allows front matter in .md files
  # docs: https://python-markdown.github.io/extensions/meta_data/
  
  - smarty
  # Smarty Pants | "converts ASCII dashes, quotes and ellipses to their HTML entity equivalents"
  # docs: https://python-markdown.github.io/extensions/smarty/
  #  and: https://daringfireball.net/projects/smartypants/
    
  - tables
  # Tables | "ability to create tables"
  # docs: https://python-markdown.github.io/extensions/tables/
  
  - toc:
# # Table of Contents | "generates a Table of Contents"
# # docs: https://python-markdown.github.io/extensions/toc/
        permalink: 🎣
        slugify: !!python/name:pymdownx.slugs.uslugify

  - mkdcomments

## Plugins #####################################

plugins:
# docs: https://www.mkdocs.org/user-guide/configuration/#plugins
#  and: https://www.mkdocs.org/user-guide/plugins/ (mostly re: development)
# list of 3rd party: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
  - search
  # Revision date, localized (Material Theme)
  # docs: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date-localized
  
  #- git-revision-date
  # displaying the date a document was last updated at the bottom of each page
  - git-revision-date-localized:
  # adds support for adding a localized last updated date at
  # the bottom of each page
      type: timeago 
      #options: date, datetime, iso_date, iso_datetime and timeago
      fallback_to_build_date: true
  
  













